# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_pizza_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='pizzas.Ingrediente'),
        ),
    ]
